version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      transport.host: 0.0.0.0
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    stdin_open: true
    tty: true
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
  enterprise-ui:
    image: octoperf/enterprise-ui:7.3.2
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  enterprise-edition:
    image: octoperf/enterprise-edition:7.3.2
    environment:
      elasticsearch.hostname: elasticsearch
      JAVA_OPTS: -Xmx256m
      rancher.project: ${RANCHER_ENVIRONMENT}
      rancher.access-key: ${RANCHER_ACCESS_KEY}
      rancher.secret-key: ${RANCHER_SECRET_KEY}
      server.hostname: ${BACKEND_HOSTNAME}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    volumes:
      - ${OCTOPERF_DATA}:/root/data
      - ${OCTOPERF_CONFIG}:/root/config
      - ${OCTOPERF_LICENSE}:/root/license
  load-balancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
      - 8090:8090/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      
volumes:
  elasticsearch-data:
    driver: local
  octoperf-data:
    driver: local
