version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      transport.host: 0.0.0.0
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    stdin_open: true
    tty: true
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    labels:
      io.rancher.container.pull_image: always
  enterprise-ui:
    image: octoperf/enterprise-ui:6.4.2
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  enterprise-edition:
    image: octoperf/enterprise-edition:6.4.2
    environment:
      rancher.hostname: ${RANCHER_HOSTNAME}
      elasticsearch.hostname: elasticsearch
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  load-balancer:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - 8090:8090/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
