version: '2'
catalog:
  name: OctoPerf Enterprise-Edition
  version: 6.4.3
  minimum_rancher_version: v1.6.0
  maximum_rancher_version: v1.6.99
  questions:
    - variable: RANCHER_ENVIRONMENT
      label: Rancher Environment
      description: Rancher Environment used to run load tests.
      default: Default
      required: true
      type: string
    - variable: RANCHER_ACCESS_KEY
      label: Rancher Access-Key
      description: Account Access-Key when Rancher is secured. Leave empty if none required.
      default: 
      required: false
      type: string
    - variable: RANCHER_SECRET_KEY
      label: Rancher Secret-Key
      description: Account Secret-Key when Rancher is secured. Leave empty if none required.
      default: 
      required: false
      type: string

services:
  elasticsearch:
    retain_ip: true
    scale: 1
    start_on_create: true
  enterprise-ui:
    scale: 1
    start_on_create: true
  enterprise-edition:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: /app
        priority: 1
        protocol: http
        service: enterprise-ui
        source_port: 8090
        target_port: 80
      - hostname: ''
        path: ''
        priority: 2
        protocol: http
        service: enterprise-edition
        source_port: 8090
        target_port: 8090
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
