version: '2'
catalog:
  name: OctoPerf Enterprise-Edition
  version: 9.0.0-rc1
  minimum_rancher_version: v1.6.16
  maximum_rancher_version: v1.6.99
  questions:
    - variable: BACKEND_HOSTNAME
      label: Server Hostname
      description: "Either Public or Private Hostname / IP accessible from load-generators. Examples: 192.168.0.10, octoperf.mycompany.com."
      default: 
      required: true
      type: string
    - variable: BACKEND_PORT
      label: Server Port
      description: "Server listening port. 8090 by default."
      default: 8090
      required: true
      type: string
    - variable: OCTOPERF_DATA
      label: OctoPerf Data Location
      description: "Warning: any change may result in data loss. By default, octoperf-data local volume. Example: /home/ubuntu/octoperf/data."
      default: octoperf-data
      required: true
      type: string
    - variable: ELASTICSEARCH_DATA
      label: Elasticsearch Data Location
      description: "Warning: any change may result in data loss. By default, elasticsearch-data local volume. Example: /home/ubuntu/octoperf/elasticsearch."
      default: elasticsearch-data
      required: true
      type: string
    - variable: OCTOPERF_LICENSE
      label: OctoPerf License Location
      description: "Where is the License located? octoperf-data volume by default. Example: /home/ubuntu/octoperf/license."
      default: octoperf-data
      required: true
      type: string
    - variable: OCTOPERF_CONFIG
      label: OctoPerf Config Location
      description: "Where is the backend config folder? octoperf-data volume by default. Example: /home/ubuntu/octoperf/config."
      default: octoperf-data
      required: true
      type: string

services:
  elasticsearch:
    retain_ip: true
    scale: 1
    start_on_create: true
  enterprise-ui:
    scale: 1
    start_on_create: true
  enterprise-edition:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        defaults
        compression algo gzip
        compression type application/json text/html text/plain
      port_rules:
      - hostname: ''
        path: /app
        priority: 1
        protocol: http
        service: enterprise-ui
        source_port: ${BACKEND_PORT}
        target_port: 80
      - hostname: ''
        path: /doc
        priority: 1
        protocol: http
        service: enterprise-documentation
        source_port: ${BACKEND_PORT}
        target_port: 80
      - hostname: ''
        path: ''
        priority: 2
        protocol: http
        service: enterprise-edition
        source_port: ${BACKEND_PORT}
        target_port: ${BACKEND_PORT}
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
