name: OctoPerf Enterprise-Edition
description: |
  Load Testing Tool for Web and Mobile Applications
version: 8.2.0
category: Load Testing Tools
maintainer: Jerome Loisel
license: Copyright OctoPerf - All Rights Reserved
projectURL: https://octoperf.com
