name: OctoPerf Enterprise-Edition
description: |
  Load Testing Tool
version: 1.0.0
category: Load Testing Tools
maintainer: Jerome Loisel
license: Copyright OctoPerf - All Rights Reserved
projectURL: https://octoperf.com
