name: OctoPerf Enterprise-Edition
description: |
  Load Testing Tool for Web and Mobile Applications
version: 9.0.0
category: Load Testing Tools
maintainer: OctoPerf
license: Copyright OctoPerf - All Rights Reserved
projectURL: https://octoperf.com
